tls_server_config:
  cert_file: /etc/node-exporter/node_exporter.crt
  key_file: /etc/node-exporter/node_exporter.key
basic_auth_users:
  prometheus: $2y$10$xeA08yvpQPj6duO3kZH/me77mqC3xnh/CGamnPBlj6UjpRNQL7K/m
