global:
  scrape_interval:     5s 
  evaluation_interval: 300s
  external_labels:
      monitor: 'otus'
      site: 'prod'

remote_write:
  - url: http://localhost:8428/api/v1/write

rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "localhost:9093"

scrape_configs:
  - job_name: 'prometheus'
    scheme: https
    basic_auth:
      username: prometheus
      password: Pa$$w0rd
    tls_config:
      ca_file: prometheus.crt
      insecure_skip_verify: true
    static_configs:
         - targets:
           - localhost:9090
  - job_name: 'node_exporter'
    scheme: https
    basic_auth:
      username: prometheus
      password: Pa$$w0rd
    tls_config:
      ca_file: node_exporter.crt
      insecure_skip_verify: true
    static_configs:
         - targets:
           - localhost:9100
  - job_name: 'mysql_exporter'
    static_configs:
         - targets:
           - localhost:9104
  - job_name: 'docker_exporter'
    static_configs:
         - targets:
           - localhost:9417
  - job_name: 'nginx_exporter'
    static_configs:
         - targets:
           - localhost:9113
  - job_name: 'victoriametrics'
    static_configs:
         - targets:
           - localhost:8428
  - job_name: 'cadvisor'
    static_configs:
         - targets:
           - localhost:8080
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://boyanchuk.com/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: "localhost:9115"
      - target_label: region
        replacement: "local"
